#!/usr/bin/env python3
"""
Search arXiv for new video hallucination papers and generate new_papers.md.

Designed to run in GitHub Actions on a monthly schedule.
"""

import json
import os
import re
import time
from datetime import datetime, timedelta

import feedparser
import requests

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README_PATH = os.path.join(REPO_ROOT, "README.md")
KNOWN_PAPERS_PATH = os.path.join(REPO_ROOT, "data", "known_papers.json")
OUTPUT_PATH = os.path.join(REPO_ROOT, "new_papers.md")

ARXIV_API_URL = "http://export.arxiv.org/api/query"

SEARCH_QUERIES = [
    'all:"video hallucination"',
    'all:"video LLM hallucination"',
    'all:"multimodal hallucination" AND all:video',
    'all:"temporal hallucination" AND all:video',
    'all:hallucination AND all:"video understanding"',
    'all:hallucination AND all:"video language model"',
]

MAX_RESULTS_PER_QUERY = 50
SEARCH_DAYS = 30
REQUEST_DELAY = 3


def extract_arxiv_ids_from_readme(readme_path):
    """Extract arXiv IDs from README.md by matching arxiv.org/abs/ links."""
    if not os.path.exists(readme_path):
        return set()
    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()
    pattern = r"arxiv\.org/abs/(\d{4}\.\d{4,5})"
    return set(re.findall(pattern, content))


def load_known_papers(path):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return set(data.get("arxiv_ids", []))
    return set()


def save_known_papers(path, arxiv_ids):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    data = {
        "last_updated": datetime.utcnow().strftime("%Y-%m-%d"),
        "arxiv_ids": sorted(arxiv_ids),
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def search_arxiv(query, max_results=50):
    """Query the arXiv API and return parsed feed entries."""
    params = {
        "search_query": query,
        "start": 0,
        "max_results": max_results,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    }
    resp = requests.get(ARXIV_API_URL, params=params, timeout=30)
    resp.raise_for_status()
    feed = feedparser.parse(resp.text)
    return feed.entries


def extract_arxiv_id(entry):
    """Extract the bare arXiv ID (e.g. '2412.03735') from a feed entry."""
    match = re.search(r"(\d{4}\.\d{4,5})", entry.id)
    return match.group(1) if match else None


def extract_github_links(text):
    """Find GitHub repo URLs in text (abstract, comments, etc.)."""
    pattern = r"https?://github\.com/[\w\-\.]+/[\w\-\.]+"
    seen = set()
    result = []
    for m in re.findall(pattern, text):
        url = m.rstrip(".")
        if url not in seen:
            seen.add(url)
            result.append(url)
    return result


def format_date(entry):
    published = entry.get("published", "")
    try:
        dt = datetime.strptime(published[:10], "%Y-%m-%d")
        return dt.strftime("%m/%Y")
    except (ValueError, IndexError):
        return "N/A"


def clean_text(text):
    """Collapse whitespace and strip."""
    return re.sub(r"\s+", " ", text.replace("\n", " ")).strip()


def generate_new_papers_md(papers, output_path):
    today = datetime.utcnow().strftime("%Y-%m-%d")

    lines = [
        f"# New Papers Found ({today})",
        "",
        "> Auto-generated by `arxiv_search.py`. "
        "Please review and classify into the appropriate sections in `README.md`.",
        "",
        f"**{len(papers)} new paper(s) found.**",
        "",
    ]

    for paper in papers:
        abstract_preview = paper["abstract"]
        if len(abstract_preview) > 200:
            abstract_preview = abstract_preview[:200] + "..."

        lines.append(f'### [{paper["title"]}]({paper["url"]})')
        lines.append("")
        lines.append(f'- **arXiv ID:** `{paper["arxiv_id"]}`')
        lines.append(f'- **Date:** {paper["date"]}')

        if paper["github_links"]:
            links_str = " | ".join(
                f"[Code]({link})" for link in paper["github_links"]
            )
            lines.append(f"- **Code:** {links_str}")
        else:
            lines.append("- **Code:** -")

        lines.append(f"- **Abstract:** {abstract_preview}")
        lines.append("")
        lines.append("---")
        lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    known_ids = load_known_papers(KNOWN_PAPERS_PATH)
    readme_ids = extract_arxiv_ids_from_readme(README_PATH)
    all_known_ids = known_ids | readme_ids

    print(
        f"Known papers: {len(all_known_ids)} "
        f"(JSON: {len(known_ids)}, README: {len(readme_ids)})"
    )

    # Collect entries from all queries, dedup by arXiv ID
    all_entries: dict = {}
    for query in SEARCH_QUERIES:
        print(f"Searching: {query}")
        try:
            entries = search_arxiv(query, MAX_RESULTS_PER_QUERY)
            for entry in entries:
                arxiv_id = extract_arxiv_id(entry)
                if arxiv_id and arxiv_id not in all_entries:
                    all_entries[arxiv_id] = entry
        except Exception as e:
            print(f"  Error querying arXiv: {e}")
        time.sleep(REQUEST_DELAY)

    print(f"Total unique papers from arXiv: {len(all_entries)}")

    cutoff = datetime.utcnow() - timedelta(days=SEARCH_DAYS)
    new_papers = []

    for arxiv_id, entry in all_entries.items():
        if arxiv_id in all_known_ids:
            continue

        published = entry.get("published", "")
        try:
            pub_date = datetime.strptime(published[:10], "%Y-%m-%d")
            if pub_date < cutoff:
                continue
        except (ValueError, IndexError):
            pass

        title = clean_text(entry.get("title", ""))
        abstract = clean_text(entry.get("summary", ""))
        url = f"https://arxiv.org/abs/{arxiv_id}"
        date = format_date(entry)

        # Look for GitHub links in abstract and arxiv_comment
        search_text = abstract
        comment = entry.get("arxiv_comment", "")
        if comment:
            search_text += " " + comment
        github_links = extract_github_links(search_text)

        new_papers.append(
            {
                "arxiv_id": arxiv_id,
                "title": title,
                "url": url,
                "date": date,
                "abstract": abstract,
                "github_links": github_links,
            }
        )

    new_papers.sort(key=lambda p: p["arxiv_id"], reverse=True)
    print(f"New papers found: {len(new_papers)}")

    if new_papers:
        generate_new_papers_md(new_papers, OUTPUT_PATH)
        print(f"Output written to {OUTPUT_PATH}")
    else:
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            f.write("")
        print("No new papers found.")

    # Persist all seen IDs so future runs skip them
    all_known_ids.update(all_entries.keys())
    save_known_papers(KNOWN_PAPERS_PATH, all_known_ids)
    print(f"Updated known papers: {len(all_known_ids)}")

    # Expose count to GitHub Actions
    gh_output = os.environ.get("GITHUB_OUTPUT")
    if gh_output:
        with open(gh_output, "a") as f:
            f.write(f"new_papers_count={len(new_papers)}\n")


if __name__ == "__main__":
    main()
