#!/usr/bin/env python3
"""Generate the standalone LaTeX taxonomy tree from data/papers.json."""

import argparse
import json
import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = REPO_ROOT / "data" / "papers.json"
OUTPUT_PATH = REPO_ROOT / "figs" / "taxonomy_tree.tex"

TAXONOMY = [
    (
        "Dynamic Distortion",
        "metaD",
        [
            (
                "Spatiotemporal Dynamics",
                "L1T",
                "T",
                [
                    ("Event Misordering", "Order", "tempEM"),
                    ("Duration Distortion", "Dur", "tempDD"),
                    ("Frequency Confusion", "Freq", "tempFC"),
                ],
            ),
            (
                "Referential Inconsistency",
                "L1A",
                "A",
                [
                    ("Character Conflation", "Char", "aggrCA"),
                    ("Scene Conflation", "Scn", "aggrSA"),
                ],
            ),
        ],
    ),
    (
        "Content Fabrication",
        "metaF",
        [
            (
                "Context-Driven Fabrication",
                "L1C",
                "C",
                [
                    ("Object-Action Hallucination", "Obj-Act", "coocOA"),
                    ("Scene-Event Hallucination", "Scn-Evt", "coocSE"),
                    (
                        "Compositional and Factuality Hallucination",
                        "Comp-Fact",
                        "coocSE",
                    ),
                    ("Both Object-Action & Scene-Event", "Both", "coocOA"),
                ],
            ),
            (
                "Audio-Visual Conflict",
                "L1V",
                "V",
                [
                    ("Action Attribution", "Act", "audioAA"),
                    ("Emotion Inference", "Emo", "audioEI"),
                ],
            ),
        ],
    ),
]

CATEGORY_LABELS = {
    "Spatiotemporal Dynamics": r"\textbf{Spatiotemporal}\\\textbf{Dynamics}",
    "Referential Inconsistency": r"\textbf{Referential}\\\textbf{Inconsistency}",
    "Context-Driven Fabrication": r"\textbf{Context-Driven}\\\textbf{Fabrication}",
    "Audio-Visual Conflict": r"\textbf{Audio-Visual}\\\textbf{Conflict}",
}

SUBTYPE_LABELS = {
    "Event Misordering": "Event Misordering",
    "Duration Distortion": "Duration Distortion",
    "Frequency Confusion": "Frequency Confusion",
    "Character Conflation": "Character Conflation",
    "Scene Conflation": "Scene Conflation",
    "Object-Action Hallucination": "Object--Action",
    "Scene-Event Hallucination": "Scene--Event",
    "Compositional and Factuality Hallucination": r"Compositional \& Factuality",
    "Both Object-Action & Scene-Event": r"Object--Action \& Scene--Event",
    "Action Attribution": "Action Attribution",
    "Emotion Inference": "Emotion Inference",
}

PREAMBLE = r"""% AUTO-GENERATED by scripts/generate_taxonomy_tree.py from data/papers.json.
% Do not edit paper labels manually; update the JSON data and regenerate this file.
\documentclass[tikz,border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[edges]{forest}
\usepackage{xcolor}
\usetikzlibrary{patterns}

\definecolor{tempEM}{HTML}{0D47A1}
\definecolor{tempDD}{HTML}{1976D2}
\definecolor{tempFC}{HTML}{42A5F5}
\definecolor{coocOA}{HTML}{E65100}
\definecolor{coocSE}{HTML}{FF9800}
\definecolor{aggrCA}{HTML}{1B5E20}
\definecolor{aggrSA}{HTML}{43A047}
\definecolor{audioAA}{HTML}{6A1B9A}
\definecolor{audioEI}{HTML}{AB47BC}
\definecolor{metaDistort}{HTML}{00838F}
\definecolor{metaFabric}{HTML}{C2185B}

\begin{document}
\begin{forest}
  for tree={
    grow'=0,
    rounded corners=2pt,
    line width=0.8pt,
    align=center,
    inner xsep=5pt,
    inner ysep=3pt,
    l sep=4mm,
    s sep=1mm,
    edge={draw=gray!45, line width=0.6pt},
    forked edge,
    font=\small\sffamily,
    text=black,
    anchor=west,
    child anchor=west,
    parent anchor=east,
  },
  root/.style={fill=gray!12, draw=gray!40, font=\bfseries\normalsize\sffamily, align=center, inner xsep=10pt, inner ysep=10pt, rotate=90, anchor=center, tier=root},
  metaD/.style={fill=metaDistort!18, draw=metaDistort!60, font=\bfseries\small\sffamily, align=center, tier=meta, inner xsep=8pt, inner ysep=5pt},
  metaF/.style={fill=metaFabric!18, draw=metaFabric!60, font=\bfseries\small\sffamily, align=center, tier=meta, inner xsep=8pt, inner ysep=5pt},
  L1T/.style={fill=tempFC!30, draw=tempFC!60, font=\bfseries\small\sffamily, align=center, tier=L1, inner xsep=9pt, inner ysep=6pt},
  L1C/.style={fill=coocSE!25, draw=coocSE!55, font=\bfseries\small\sffamily, align=center, tier=L1, inner xsep=9pt, inner ysep=6pt},
  L1A/.style={fill=aggrSA!25, draw=aggrSA!55, font=\bfseries\small\sffamily, align=center, tier=L1, inner xsep=9pt, inner ysep=6pt},
  L1V/.style={fill=audioEI!25, draw=audioEI!55, font=\bfseries\small\sffamily, align=center, tier=L1, inner xsep=9pt, inner ysep=6pt},
  L2T/.style={fill=tempFC!18, draw=tempFC!45, font=\small\sffamily, align=center, tier=L2, inner xsep=7pt, inner ysep=4pt},
  L2C/.style={fill=coocSE!15, draw=coocSE!40, font=\small\sffamily, align=center, tier=L2, inner xsep=7pt, inner ysep=4pt},
  L2A/.style={fill=aggrSA!15, draw=aggrSA!40, font=\small\sffamily, align=center, tier=L2, inner xsep=7pt, inner ysep=4pt},
  L2V/.style={fill=audioEI!15, draw=audioEI!40, font=\small\sffamily, align=center, tier=L2, inner xsep=7pt, inner ysep=4pt},
  benchT/.style={fill=tempFC!10, draw=tempFC!30, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  benchC/.style={fill=coocSE!8, draw=coocSE!28, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  benchA/.style={fill=aggrSA!8, draw=aggrSA!28, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  benchV/.style={fill=audioEI!8, draw=audioEI!28, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  methT/.style={pattern=north east lines, pattern color=tempFC!30, draw=tempFC!35, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  methC/.style={pattern=north east lines, pattern color=coocSE!25, draw=coocSE!30, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  methA/.style={pattern=north east lines, pattern color=aggrSA!25, draw=aggrSA!30, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
  methV/.style={pattern=north east lines, pattern color=audioEI!25, draw=audioEI!30, line width=0.7pt, font=\scriptsize\sffamily, align=left, tier=L3, inner xsep=5pt, inner ysep=3pt},
"""

POSTAMBLE = r"""\end{forest}
\end{document}
"""


def latex_escape(text):
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in text)


def wrap_entries(entries, width=92):
    items = [f"{latex_escape(p['name'])} ({p['year']})" for p in entries]
    lines = []
    current = []
    current_length = 0
    for item in items:
        separator_length = 2 if current else 0
        if current and current_length + separator_length + len(item) > width:
            lines.append(", ".join(current))
            current = [item]
            current_length = len(item)
        else:
            current.append(item)
            current_length += separator_length + len(item)
    if current:
        lines.append(", ".join(current))
    return r",\\".join(lines)


def load_entries():
    with DATA_PATH.open(encoding="utf-8") as handle:
        data = json.load(handle)
    entries = data["entries"]
    supported = {
        (category, subtype)
        for _, _, categories in TAXONOMY
        for category, _, _, subtypes in categories
        for subtype, _, _ in subtypes
    }
    actual = {(p["category"], p["subtype"]) for p in entries}
    if actual != supported:
        missing = sorted(actual - supported)
        unused = sorted(supported - actual)
        raise ValueError(
            f"Taxonomy mapping mismatch; missing={missing}, unused={unused}"
        )
    return entries


def build_tree(entries):
    lines = ["  [{Vid-LLM Hallucination}, root"]
    used_ids = []
    for meta_name, meta_style, categories in TAXONOMY:
        meta_label = r"\\".join(
            f"\\textbf{{{part}}}" for part in meta_name.split(" ", 1)
        )
        lines.append(f"    [{{{meta_label}}}, {meta_style}")
        for category, category_style, family, subtypes in categories:
            lines.append(f"      [{{{CATEGORY_LABELS[category]}}}, {category_style}")
            for subtype, short_label, short_color in subtypes:
                subtype_label = SUBTYPE_LABELS[subtype]
                lines.append(
                    "        "
                    f"[{{{subtype_label} "
                    f"({{\\footnotesize\\textcolor{{{short_color}}}{{{short_label}}}}})}}, "
                    f"L2{family}"
                )
                for paper_type, style_prefix in (
                    ("benchmark", "bench"),
                    ("mitigation", "meth"),
                ):
                    papers = [
                        p
                        for p in entries
                        if p["category"] == category
                        and p["subtype"] == subtype
                        and p["type"] == paper_type
                    ]
                    if not papers:
                        continue
                    used_ids.extend(p["id"] for p in papers)
                    lines.append(
                        f"          [{{{wrap_entries(papers)}}}, "
                        f"{style_prefix}{family}]"
                    )
                lines.append("        ]")
            lines.append("      ]")
        lines.append("    ]")
    lines.append("  ]")

    expected_ids = [p["id"] for p in entries]
    if sorted(used_ids) != sorted(expected_ids):
        raise ValueError("Generated tree does not cover every data entry exactly once")
    return "\n".join(lines) + "\n"


def generate():
    entries = load_entries()
    source = PREAMBLE + build_tree(entries) + POSTAMBLE
    return source, entries


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated LaTeX source is not up to date.",
    )
    args = parser.parse_args()

    source, entries = generate()
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text() != source:
            raise SystemExit("Taxonomy LaTeX source is out of date")
        print(f"Taxonomy source is current: {len(entries)} entries")
        return

    os.makedirs(OUTPUT_PATH.parent, exist_ok=True)
    OUTPUT_PATH.write_text(source)
    benchmarks = sum(p["type"] == "benchmark" for p in entries)
    mitigations = sum(p["type"] == "mitigation" for p in entries)
    print(
        f"Generated {OUTPUT_PATH}: {len(entries)} entries "
        f"({benchmarks} benchmarks, {mitigations} mitigations)"
    )


if __name__ == "__main__":
    main()
